# Generated by Django 5.2.1 on 2025-05-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='category_name_d601b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='product_name_c4c985_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Product ↔ Categories',
                'db_table': 'product_category',
                'ordering': ['product', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'receipt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='receipt_created_4c99c4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='total_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventorybatch')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.receipt')),
            ],
            options={
                'db_table': 'receipt_product',
                'ordering': ['receipt', 'batch'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['product', 'expiration_date'], name='inventory_b_product_518133_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='batch_quantity_gte_0'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['product', 'category'], name='product_cat_product_1e61a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
        migrations.AddConstraint(
            model_name='receiptproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='receiptproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_purchase__gte', 0)), name='price_at_purchase_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptproduct',
            unique_together={('receipt', 'batch')},
        ),
    ]
