# Generated by Django 5.2.1 on 2025-05-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatch',
            options={'ordering': ['expiration_date'], 'verbose_name_plural': 'Inventory Batches'},
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='inventory.product'),
        ),
    ]
