# Generated by Django 5.2.1 on 2025-05-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['product', 'category'], 'verbose_name_plural': 'Product ↔ Categories'},
        ),
        migrations.AlterModelOptions(
            name='receiptproduct',
            options={'ordering': ['receipt', 'product'], 'verbose_name_plural': 'Receipt ↔ Products'},
        ),
    ]
