# Generated by Django 5.2.1 on 2025-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorybatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receiptproduct',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
