# Generated by Django 5.2.1 on 2025-05-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_receipt_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptproduct',
            options={'ordering': ['receipt', 'batch'], 'verbose_name_plural': 'Receipt ↔ Products'},
        ),
    ]
